# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-21 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100)),
                ('club_email', models.EmailField(max_length=50)),
                ('club_contact', models.CharField(max_length=20)),
                ('registered_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=50)),
                ('academic_year', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('school_or_faculty', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('leadership_year', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('school_or_faculty', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('course', models.CharField(max_length=200)),
                ('club', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='club_management.Club')),
            ],
        ),
    ]
