# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-21 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='institution',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='club_management.Institution'),
        ),
    ]
