# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-22 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0002_club_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='institution',
            field=models.CharField(choices=[('1', '--Select--'), ('2', 'Brainverse Institute'), ('3', 'Brain verse college'), ('4', 'Brain Technical')], default=1, max_length=200),
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
