# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-26 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0003_auto_20200122_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='official',
            old_name='club',
            new_name='club_name',
        ),
    ]
