# Generated by Django 2.0.12 on 2020-01-29 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0004_auto_20200126_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='club',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='club_management.Club'),
        ),
    ]
